from __future__ import annotations
from typing import Protocol, TypeVar, Generic
from mission_control.domain.models import (
    Brief,
    BriefFilters,
    ReviewItem,
    CrossTaskLink,
    TimelineEvent,
    Notification,
)

T = TypeVar("T")


class Repository(Protocol, Generic[T]):
    async def get(self, id: str) -> T | None: ...
    async def list(self, **filters) -> list[T]: ...
    async def save(self, entity: T) -> T: ...
    async def delete(self, id: str) -> None: ...


class BriefRepository(Protocol):
    async def get(self, id: str) -> Brief | None: ...
    async def list(self, filters: BriefFilters) -> list[Brief]: ...
    async def save(self, brief: Brief) -> Brief: ...
    async def delete(self, id: str) -> None: ...
    async def get_by_path(self, path: str) -> Brief | None: ...
    async def get_children(self, parent_path: str) -> list[Brief]: ...
    async def search(self, query: str) -> list[Brief]: ...
    async def rebuild_index(self, briefs: list[Brief]) -> None: ...
    async def update_from_filesystem(self, path: str) -> None: ...
    async def delete_from_filesystem(self, path: str) -> None: ...


class ReviewRepository(Protocol):
    async def create(self, review: ReviewItem) -> ReviewItem: ...
    async def get(self, id: str) -> ReviewItem | None: ...
    async def list(self, status: str | None = None) -> list[ReviewItem]: ...
    async def update_feedback(self, id: str, feedback: dict) -> ReviewItem: ...
    async def delete(self, id: str) -> None: ...


class LinkRepository(Protocol):
    async def find_links(self, source_path: str) -> list[CrossTaskLink]: ...
    async def create_link(self, link: CrossTaskLink) -> CrossTaskLink: ...
    async def confirm_link(self, id: str) -> CrossTaskLink: ...
    async def dismiss_link(self, id: str) -> None: ...
    async def get_all_links(self) -> list[CrossTaskLink]: ...
    async def clear_all(self) -> None: ...


class TimelineRepository(Protocol):
    async def create(self, event: TimelineEvent) -> TimelineEvent: ...
    async def get_for_brief(self, brief_path: str) -> list[TimelineEvent]: ...
    async def list_recent(self, limit: int = 50) -> list[TimelineEvent]: ...


class NotificationRepository(Protocol):
    async def create(self, notification: Notification) -> Notification: ...
    async def get_unread(self, target_path: str | None = None) -> list[Notification]: ...
    async def mark_read(self, id: str) -> None: ...
